# Dataset Exploration Using Pandas

## Objective

To explore a dataset using Pandas functions such as `shape`, `columns`, `info()`, `describe()`, `head()`, and `tail()` to understand its structure and basic characteristics before modeling.

In [1]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["species"] = [iris.target_names[i] for i in iris.target]

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
print("First Five Rows:")
display(df.head())

First Five Rows:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [4]:
print("Last Five Rows:")
display(df.tail())

Last Five Rows:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [5]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
print("Dataset Shape:", df.shape)

Number of Rows: 150
Number of Columns: 5
Dataset Shape: (150, 5)

In [6]:
print("Column Names:")
print(df.columns.tolist())

Column Names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']

In [7]:
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [8]:
print("Summary Statistics:")
display(df.describe())

Summary Statistics:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [9]:
numerical_columns = df.select_dtypes(include="number").columns.tolist()
categorical_columns = df.select_dtypes(include="object").columns.tolist()

print("Numerical Columns:", numerical_columns)
print("Categorical Columns:", categorical_columns)

Numerical Columns: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Categorical Columns: ['species']

In [10]:
print("Species Counts:")
print(df["species"].value_counts())

Species Counts:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [11]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

Missing Values in Each Column:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

## Observations

1. The dataset contains 150 rows and 5 columns.
2. The dataset contains four numerical features and one categorical column.
3. The numerical features are sepal length, sepal width, petal length, and petal width.
4. The species column contains three categories: setosa, versicolor, and virginica.
5. Each species has 50 observations.
6. The dataset contains no missing values.
7. The `describe()` function provides summary statistics for the numerical columns.